model:
  base_learning_rate: 1.0e-05
  target: ldm.models.diffusion.ddpm.TwoStreamControlLDM
  params:
    linear_start: 0.00085
    linear_end: 0.012
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    control_key: hint
    image_size: 64
    channels: 4
    cond_stage_trainable: false
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: false
    sync_path: /PATH/TO/STABLE_DIFFUSION/v1-5-pruned.ckpt                         #  path to the StableDiffusion v 1.5 weights
    synch_control: false
    ckpt_path_ctr: null
    control_mode: canny
    control_stage_config:
      target: ldm.modules.diffusionmodules.twoStreamControl.TwoStreamControlNet
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        hint_channels: 3
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
        infusion2control: cat
        infusion2base: add
        guiding: encoder_double
        two_stream_mode: cross
        control_model_ratio: 0.2
        learn_embedding: false
        fixed: true
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 320
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        - 4
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 768
        use_checkpoint: true
        legacy: false
    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.FrozenCLIPEmbedder

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.dummy_set.DummyBase
      params:
        size: 512
        data_root: /PATH/TO/TRAINING/SET
        control_mode: 'canny'
        
        
lightning:
  modelcheckpoint:
      params:
        every_n_train_steps: 5000
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 2500
        max_images: 8
        increase_log_steps: False
    metrics_over_trainsteps_checkpoint:
        every_n_train_steps: 2500

  trainer:
    benchmark: True
    accumulate_grad_batches: 1
    accelerator: ddp
    max_steps: 500000
    gpus: 0,
    devices: 0,